### ISSUE TITLE
Vibrations no longer working on 0.10.1

### ISSUE THREAD

**Issue by jadenPete** [MrCrayfish/Controllable#142]
Hello, and thanks for all the work you've put into the new releases!

OS: Windows 10 64 bit
Controller: Xbox Series X/S over Bluetooth
Minecraft Version: 1.16.5 with Forge, OptiFine HD U G6, and WorldEdit
Current Controllable version: 0.10.1
Last working Controllable version: 0.9.1

My controller no longer vibrates (e.g. when I raise my shield, eat, or fall), regardless of whether the setting is enabled.
I think it may have to do with using GLFW to handle controller input.

EDIT: Apparently, [GLFW doesn't support haptic feedback](https://github.com/glfw/glfw/issues/57), though there is a [pull request](https://github.com/glfw/glfw/pull/1678) to add it.

**Comment by MrCrayfish** [comment]
Unfortunately as mentioned GLFW does not support rumble. I knew this before switching to GLFW but thought it was a good trade off to reduce the file size of the mod. I may consider bringing back SDL until GLFW adds rumble support. (Especially since the first issue was posted in 2013 for rumble support)

**Comment by jadenPete** [comment]
Though the reduced file size is nice, I would appreciate bringing back SDL.

**Comment by MrCrayfish** [comment]
The issue referenced was reported before I implemented GLFW. I have a version of Controllable that can optionally load SDL but I don't know how to distribute the required libraries.

**Comment by jadenPete** [comment]
Can you merge the libraries into the mod jar?

**Comment by imarak2** [comment]
me too on the new version 0.20.3 it still doesn't work when i raise my shield or charge a bow i don't feel the rumble and i double checked the rumble to see if its on and it is on please comment when you can

**Comment by MrCrayfish** [comment]
In an upcoming update, Controllable will return to using SDL with a custom library maintained by myself (https://github.com/MrCrayfish/ControllableSDL). This will support rumble.

**Comment by imarak2** [comment]
> In an upcoming update, Controllable will return to using SDL with a custom library maintained by myself (https://github.com/MrCrayfish/ControllableSDL). This will support rumble.

finally bro thank you so much
