### ISSUE TITLE
Exiting Pause Menu activates ingame action

### ISSUE THREAD

**Issue by dude98** [MrCrayfish/Controllable#196]
Whenever i leave the pause menu using A or B, i do the corresponding ingame action the next frame essentially, even if i'm not wanting to. The only way to close the pause menu without causing that is to hit the inventory button, as for some reason it doesn't open it like you'd think since opening inventory is it's ingame action.

**Comment by MrCrayfish** [comment]
Fixed in https://github.com/MrCrayfish/Controllable/commit/fd077f5eece1b8a0e800dfa7c420f7fd67ccd763

**Comment by dude98** [comment]
it's not fixed entirely, hitting B when it's bound to drop still drops the item when you close the pause menu.
