### ISSUE TITLE
Iron's Spells and Spellbooks Incompatibility

### ISSUE THREAD

**Issue by Beybok** [MrCrayfish/Controllable#532]
The key bind for "Open Spell Wheel" doesn't open the spell wheel. Everything else in the mod seems to work perfectly except for this, and it's a pretty major feature.

**Comment by MagicQuartz** [comment]
I have the same issue, and also tried to change the key to a regular keyboard key and it still doesn't work.

**Comment by Reletr** [comment]
I'm also having this issue, every time I press the key my default Windows cursor briefly appears and nothing else happens. (ATM9 0.3.2)

Edit: I fixed my issue. Apparently in the Baubles menu, the spellbook is able to be put in both the Curio slots and the Spellbook slots, even though spellbooks cannot be used from the Curio slot. When both slots are empty, Shift+M1 from inventory or M2 from hand will prioritize the Curio slot.

**Comment by MawanZ** [comment]
Still have this issue. I'm on 1.20.1. What I found out is that if you wait for the controllable ui to dissapear and try to use it with a keyboard key, it works.
Its not really practical at all since I need to wait a good 10 seconds between switching spells...

**Comment by parafectivityorsomeshit** [comment]
This issue is STILL a thing. I have tried to fix it by using the toggle option, and trying to cast to see if it works. Both failed. No matter what I do, I cannot open the spell wheel. I have set it to literally every key I can. Still does not work. This one bug has turned the mod from Iron's Spells n Spellbooks, into Iron's _______ n __________.

**Comment by 754iron-stack** [comment]
hi, im having a simmilar issue and i dont even have this mod installed - the open spell wheel gui wont pop up and neither will any iron's spells gui
