### ISSUE TITLE
Forge 1.20.1 Controllable 0.21.1 crash on start up

### ISSUE THREAD

**Issue by Babyorder123** [MrCrayfish/Controllable#552]
https://mclo.gs/cCyBHoY is my log

**Comment by squigglezworth** [comment]
Here's another (smaller) log https://mclo.gs/qpKtMcs

**Comment by MrCrayfish** [comment]
Thanks for the report. Fixed in https://github.com/MrCrayfish/Controllable/commit/3186c1afae59478eb290d49194f2bdad928a7832. Patch out soon!

**Comment by squigglezworth** [comment]
I just grabbed the `0.21.2` release and am still getting a crash

https://mclo.gs/FUfH7j3

**Comment by MrCrayfish** [comment]
Sorry about that. It should now be resolved in 0.21.4
